### ISSUE TITLE
Web application initialization error

### ISSUE THREAD

**Issue by lordoftheflies** [lordoftheflies/jackrabbit#1]
Got the following output:

```
java.lang.ClassNotFoundException: /WEB-INF/protectedHandlersConfig.xml
        at java.lang.Class.forName0(Native Method) ~[na:1.8.0_65]
        at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_65]
        at org.apache.jackrabbit.server.remoting.davex.ProtectedRemoveManager.createHandler(ProtectedRemoveManager.java:92) [jackrabbit-jcr-server-2.12.1.jar:na]
        at org.apache.jackrabbit.server.remoting.davex.ProtectedRemoveManager.<init>(ProtectedRemoveManager.java:59) [jackrabbit-jcr-server-2.12.1.jar:na]
        at org.apache.jackrabbit.server.remoting.davex.JcrRemotingServlet.init(JcrRemotingServlet.java:283) [jackrabbit-jcr-server-2.12.1.jar:na]
        at javax.servlet.GenericServlet.init(GenericServlet.java:244) [servlet-api-3.1.jar:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:612) [jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:395) [jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871) [jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298) [jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349) [jetty-webapp-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342) [jetty-webapp-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505) [jetty-webapp-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41) [jetty-deploy-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:186) [jetty-deploy-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:498) [jetty-deploy-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:146) [jetty-deploy-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180) [jetty-deploy-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:440) [jetty-deploy-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64) [jetty-deploy-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:609) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:528) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.util.Scanner.scan(Scanner.java:391) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150) [jetty-deploy-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:560) [jetty-deploy-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:235) [jetty-deploy-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.Server.start(Server.java:387) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.Server.doStart(Server.java:354) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1255) [jetty-xml-9.2.9.v20150224.jar:9.2.9.v20150224]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_65]
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1174) [jetty-xml-9.2.9.v20150224.jar:9.2.9.v20150224]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:321) [start.jar:9.2.9.v20150224]
        at org.eclipse.jetty.start.Main.start(Main.java:817) [start.jar:9.2.9.v20150224]
        at org.eclipse.jetty.start.Main.main(Main.java:112) [start.jar:9.2.9.v20150224]
```

**Comment by lordoftheflies** [comment]
Add propertecHandlerConfig.xml under WEB-INF
